exclude: [ Readme.md, pub_drafts.rb ]
assets: /assets
pic: /assets/pics
css: /assets/css
js: /assets/js

markdown: redcarpet
redcarpet:
    extensions: [ "no_intra_emphasis","tables","fenced_code_blocks","autolink","strikethrough","underline","hightlight","footnote"]

permalink: pretty
paginate: 10
paginate_path: "posts/page:num"